name: Release

on:
  push:
    tags:
      - "v*" # Triggers the workflow on version tags like v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: ".exe"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build the project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary for release
        run: |
          mkdir -p release
          zip -j release/weaveconfig-${{ matrix.target }}.zip target/${{ matrix.target }}/release/weaveconfig${{ matrix.extension }}
        shell: bash

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/weaveconfig-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
